.TH ROPIPE 1 "07 July 2024"
.SH NAME
ropipe - Convert Roman numerals to integers and vice-versa in pipes
.SH SYNOPSIS
ropipe [ -rskqh ]
.SH DESCRIPTION
Ropipe converts decimal integers to Roman numerals and vice versa, reading from stdin and printing to stdout. It is meant to primarily be used in pipes. By default, it converts integers to Roman numerals.
.SS Options
.TP
-r
Convert Roman numerals to integers. Integer to Roman is the default.
.TP
-s
Fails silently, with no output on invalid input.
.TP
-k
Don't quit on invalid input; continue processing subsequent inputs.
.TP
-q
Accept quirky Roman numerals like IIII for IV.
.TP
-h
Display this help message.
.SH FILES
.TP
/usr/bin/ropipe
The program
.SH BUGS
Send bug reports to https://github.com/MatMasIt/ropipe
