.TH ROPIPE 1 "06 October 2021"
.SH NAME
ropipe - Convert roman numbers to integers and vice-versa in pipes
.SH SYNOPSIS
ropipe [ -r ]
.SH DESCRIPTION
Ropipe converts decimal integers to roman numbers and vice versa, reading from stdin and printing to stdout, it is meant to primarily be used in pipes.
Default is integer to roman.
.SS Options
.TP
-r
Roman to integer. Integer to roman is the default.
.SH FILES
.TP
/usr/bin/ropipe
The program
.SH BUGS
Send bug reports to https://github.com/MatMasIt/ropipe
